### ISSUE TITLE
Feature request: more filter options

### ISSUE THREAD

**Issue by BevansDesign** [smaitch/Wholly#1]
I'd love to have the ability to hide quests I can't do on my character. Currently I'm seeing tons of quests that I can't do because I'm either the wrong class or wrong profession.

Thanks!

**Comment by smaitch** [comment]
As Grail is updated with proper tagging of quests to be of specific classes or professions they will automatically be filtered out.  If you have specific quests you should not be seeing please indicate them so they can be tackled sooner.
