### ISSUE TITLE
Too many subzones in Other section

### ISSUE THREAD

**Issue by javierhimura** [smaitch/Wholly#10]
I have notice that in the "others" section, where there is zones for dungeons, scenarios and other things, there are too many subzones, it is currently impossible for my to select any subzone that start with letter between A and K, because from K to Z there are enought zones that fill all th screen

There is the same problem with reputations, there are too many.

It would be possible to separate this groups in subgroups based on expansion? Or at least separate in two groups with one from A to M and another from M to Z, like Kalimdor and Eastern Kingdoms.

**Comment by smaitch** [comment]
Ahh, you must not be using wide mode for the Wholly panel.  I will experiment with the Others section and others to see what needs the multiple entry treatment like Kalimdor.

**Comment by smaitch** [comment]
With the latest version of Grail the zones that Blizzard was not returning properly have been put into their continents so the Other section is much smaller.
