### ISSUE TITLE
Wrong map representation of quest type

### ISSUE THREAD

**Issue by Darakah** [smaitch/Wholly#11]
Hello,

Since the latest version (for 8.0), wholly is messing up the representation type: ! and ? and ! (normal quest, repeatable and daily types respectively). it just changes them, can't see a pattern, sometimes when i click on zone it is all repeatable or daily and so on. note that once i place cursor over a quest it shows properly (the correct color name of the quest but still wrong representation, it is also listed correctly in the wholly panel of quest lists for the zone). and if i go into the selection and remove repeatable, still once i go back to map there are non-repeatable quests (normal) represented as the ? mark.

deleted and re-downloaded did not help. any help would be greatly appreciated. Thanks a lot for this add-on, it is amazingly important and nice. and good job on the improved form of the quest things on the map much better then the old ones.

Thanks for the help.

**Comment by smaitch** [comment]
The latest version of Wholly should correct this issue.
