### ISSUE TITLE
Pins not showing on map

### ISSUE THREAD

**Issue by Zaithe** [smaitch/Wholly#13]
I'm in ashenvale and not seeing the quest pins showing on my map. I read the instructions and it seems like it should be working and enabled all filters ect and bound toggle map pins to a button and its not working. This problem is also happening with my friend who tried it.

**Comment by smaitch** [comment]
Is this only happening in Ashenvale?  Do the quests show up in the Wholly quest panel list?

**Comment by smaitch** [comment]
I have not been able to reproduce the problem.  I have tried with characters both with tons of quests completed and those who have started anew, and I see map pins in Ashenvale.  As I have gotten no other feedback I will close this ticket.
