### ISSUE TITLE
Wholly button covers Cursor Coords

### ISSUE THREAD

**Issue by bolerro** [smaitch/Wholly#14]
In the map, the Wholly button to remove quest giver icons covers up the Cursor Coordinates

[![Screenshot from Gyazo](https://gyazo.com/cc046e3f13235fdefbf75449ddab271a/raw)](https://gyazo.com/cc046e3f13235fdefbf75449ddab271a)

**Comment by smaitch** [comment]
What addon are you using to display the cursor coordinates?  Wholly should already move itself over from the TomTom coordinates in the map.

**Comment by bolerro** [comment]
As far as I am aware, I’m not using a map add on. So it should be just the default UI world map.

**Comment by bolerro** [comment]
Only other idea is maybe Titan or Broker: Everything could be injecting into the map UI

**Comment by bolerro** [comment]
Check those two addons and found that its the Titan Location addon that shows the cursor coordinates. Those coordinates sit underneath the Wholly button. So not sure now where this would be fixed. Through Wholly or through Titan

**Comment by smaitch** [comment]
The latest version of Wholly that was pushed to GitHub should have a fix that permits Wholly's map panel button and Titan Location to work together.  As a side note, I see that both Titan Panel and TomTom do not work together at this location.
