### ISSUE TITLE
\AddOns\Wholly\Wholly.lua line 3031:    attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Wholly#15]
On the 8.2 PTR i get this stacktrace on occasion:

`Message: ..\AddOns\Wholly\Wholly.lua line 3031:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   Wholly\Wholly.lua:3031: _PopulateTooltipForQuest()
   Wholly\Wholly.lua:3153: QuestInfoEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:`

**Comment by smaitch** [comment]
I think this is no longer an issue with the latest versions of Wholly and Grail.
