### ISSUE TITLE
Wholly not displaying completed quests in WoW Classic

### ISSUE THREAD

**Issue by reaktorblue** [smaitch/Wholly#16]
I have Wholly 071 and Grail 100 installed and what I'd like to be able to do is simply see a list of quests I've already completed.

I'm not entirely sure what I'm doing wrong, I can't get any quests to populate. I've spent two days researching the issue to see if I installed something incorrectly or if I have to initialize a command or something but haven't been able to locate a solution. All folders were installed to the AddOns folder and are visible within the AddOns menu in game. The /grail help options work and /wholly works but none of the quests I've currently completed appear.

Could someone help point me in the right direction?

**Comment by smaitch** [comment]
Grail has been updated on GitHub such that the need to manually issue the /grail slash command should no longer be needed.

@reaktorblue Please send your Grail.lua saved variables file so we can update the Grail database with all the quest information you have gathered.

**Comment by smaitch** [comment]
Grail 101 and Wholly 072 are released to the public so should be showing quests as appropriate based on the knowledge Grail has.
