### ISSUE TITLE
Quest Icons not showing in classic

### ISSUE THREAD

**Issue by ceferrari** [smaitch/Wholly#17]
I have installed the latest versions of both Grail (100) and Wholly (071), the quests are queried succesfully but no icons are showing in my map or minimap.

**Comment by smaitch** [comment]
Wholly does not put anything in the minimap.  There have been some updates to both Wholly and Grail that are currently available on GitHub that should allow you to see map icons as expected.

**Comment by ceferrari** [comment]
Thanks for the reply @smaitch. I will download the GitHub version and test it tonight.

One thing I noticed though, Wholly GitHub's version is the same as Curse one, where I downloaded originally. Both are 071.

Any difference between them?

**Comment by yoshimo** [comment]
Minimap icons was the game itself , which won't happen in classic.
Questie has some icons to find quest locations if you are intrested in that.

**Comment by smaitch** [comment]
Currently the version on GitHub is the same as release, but there are many differences.  I hope to change the release numbers on GitHub once I am closer to a public release.

**Comment by smaitch** [comment]
Grail 101 and Wholly 072 have been released, which should be displaying quest icons where Grail has data in both Retail and Classic.
