### ISSUE TITLE
CLASSIC - 102 - Map button

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Wholly#18]
CLASSIC - 102 - Map button
This does not appear on my map, neither ordinary map or Mapster version.

Additionally, some people run Questie with your add-on. When the map button was present in previous versions, Questie's button covered yours.

**Comment by smaitch** [comment]
I see the Wholly map button on my map both with and without TomTom enabled.  I assume you have the preferences set to show the map button.  I have not tried with Mapster for ages.  In looking into this issue, I see that the Classic position with TomTom is bad, so I will make sure it just assumes the proper position.  I do not know about Questie but I can see where it puts a button and how to handle that.

**Comment by smaitch** [comment]
I just tested with Mapster and it seems fine.  In Classic the Wholly button is to the left of the zones and Mapster is to the right.  In Retail Wholly button is on left and Mapster is on the right.

**Comment by smaitch** [comment]
I just downloaded Questie and made changes so Wholly moves its button when Questie is present.  It looks like Questie does a lot of what Wholly and Grail do, with some added functionality that Wholly does not try to do.

**Comment by Nerillida** [comment]
> It looks like Questie does a lot of what Wholly and Grail do, with some added functionality that Wholly does not try to do.

True, it does, but, as far as I can see and last time that I looked, it does not have the server interrogation aspect. 
Personally, and talking to a few others, Wholly showing the turn in would do more, but I know that I have mentioned that before. Some of my group run both addons.

**Comment by smaitch** [comment]
Wholly 074 is now released.
