### ISSUE TITLE
Classic: Wholly Questlog can't display many quests properly

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Wholly#19]
When i have a lot of quests shown in Wholly, the Window can't show them properly.
![Wholly_Classic](https://user-images.githubusercontent.com/17909/66025518-f67d3800-e4f6-11e9-8367-4dbecef43afe.jpg)

**Comment by smaitch** [comment]
Yes, this is a known issue.  The Wholly quest panel is using UI objects that have changed between Classic and Retail.  A different version will be used for Classic eventually.  It is on the list of things to tackle, but is a little lower on the list as the wide version of the quest panel could be used to have a better UI experience until this is addressed.

**Comment by smaitch** [comment]
Wholly has been updated in GitHub to handle this much better in Classic.

**Comment by smaitch** [comment]
Wholly 074 is now released.
