### ISSUE TITLE
Wholly showing wrong world map pins

### ISSUE THREAD

**Issue by Altheia01** [smaitch/Wholly#2]
I'm questing in Broken Isles don't know if its just that area the addon is having an issue with. I have wholly and Grail installed. My warlock has tailoring and enchanting.  On the world map Wholly is showing pins for skinning quests also.  I never had skinning on this character I do have it on my druid.  I can't figure why its doing that sure makes it confusing. Anyone else having this issue I really like this addon.  I looked under the Wholly addon and don't see professions listed anywhere there. I have Grail installed but doesn't show up under interface >> addons. But its listed under addons.

**Comment by smaitch** [comment]
The issue is Grail does not mark the skinning quests you are seeing as skinning quests.  Wholly naturally filters out quests that are marked with professions you do not have, so the issue is with the Grail data.

**Comment by smaitch** [comment]
The latest Grail should have lots of quests marked Skinning.  Is this still a problem for you?

**Comment by smaitch** [comment]
It has been a few months now, so probably things are ok.  Time to close.
