### ISSUE TITLE
Wholly search box problem

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Wholly#22]
Several of us are finding this when attempting to start a new Wholly search.
Mac High Sierra.

![Screen Shot 2019-10-23 at 07 33 36](https://user-images.githubusercontent.com/55858788/67364483-88f98000-f567-11e9-8429-f9dce27fe3a4.png)

The vertical line flashes about one a second.

**Comment by smaitch** [comment]
This was recently fixed in the version of Wholly on GitHub.

**Comment by smaitch** [comment]
Wholly 075 is now public.
