### ISSUE TITLE
Classic error

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Wholly#34]
I am unsure if this is new or has been present for previous versions.

Using latest build of WoW classic and Grail/Wholly.

Present with no other add ons.

Repair Wow seems fine

Date: 2020-07-16 12:35:36
ID: 2
Error occured in: Global
Count: 4
Message: ..\AddOns\Wholly\Wholly.lua line 4134:
   attempt to perform arithmetic on field 'y' (a nil value)
Debug:
   Wholly\Wholly.lua:4134: ShowTooltip()
   Wholly\Wholly.lua:846:
      Wholly\Wholly.lua:846
Locals:
self = <table> {
 SortingFunction = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4213
 pinsNeedFiltering = false
 _SetupBlizzardQuestLogSupport = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3694
 configurationScript5 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:545
 _BreadcrumbQuestId = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1283
 Sort = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4184
 _SearchFrameShow = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3401
 configurationScript18 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:602
 mapPinsRegistry = <table> {
 }
 _RegisterSlashCommand = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1991
 currentMaximumTooltipLines = 50
 debug = true
 configurationScript2 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:530
 tooltip = com_mithrandir_WhollyTooltip {
 }
 SortButtonEnter = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4198
 initialUpdateProcessed = true
 dropdownText = "Orgrimmar"
 ScrollFrame_Update_WithCombatCheck = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3379
 levelTwoData = <table> {
 }
 _ColorCodeFromInfo = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1489
 ScrollFrame_Update = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3492
 _PinIndex = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1971
 cachedPanelQuests = <table> {
 }
 levelTwoCurrent = <table> {
 }
 _SetupLibDataBroker = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3783
 _SetupDefaults = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3712
 configurationScript10 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:560
 carboniteMapLoaded = false
 configurationScript15 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:579
 playerAliveReceived = false
 _HideTooltip = <function> defined @Interface\AddOns\Wholly\Wholly.lua:2008
 QuestInfoEnter = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3147
 configurationScript12 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:569
 SetCurrentZoneToPanel = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3652
 _NPCInfoSection = <function> defined @Interface\AddOns\Wholly\Wholly.lua:2491
 receivedCalendarUpdateEventList = false
 _RecordTooltipNPCs = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3267
 ShowBreadcrumbInfo = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4088
 _Dropdown_GetText = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1702
 waypoints = <table> {
 }
 configurationScript8 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:551
 _DroppedItemMatchesQuest = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1745
 _TagDeleteConfirm = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4274
 mapPinsTemplateName = "WhollyPinsTemplate"
 _GetBreadcrumbMessage = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3680
 checkedNPCs = <table> {
 }
 color = <table> {
 }
 mapPinsProvider = <table> {
 }
 _SetLevelTwoCurrent = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3668
 dropdownLimit = 40
 npcs = <table> {
 }
 _Dropdown_Create = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1691
 Click = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1452
 RegisteredMapPin = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1982
 preferenceButtons = <table> {
 }
 _DisplayMapFrame = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1668
 _ColorUpdatePreferenceText = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1518
 ToggleSwitch = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4345
 Dropdown_Initialize = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1709
 filteredPinQuests = <table> {
 }
 ScrollFrame_OnLoad = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3361
 filteredPanelQuests = <table> {
 }
 BreadcrumbClick = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1262
 BreadcrumbUpdate = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1296
 _PrettyQuestString = <function>
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  auccheapsearcher, v20190917r3
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.05
  BrokerPortals, v1.11.1
  ClassicAutoDismount, v1.01
  ClassicCastbars, vv1.3.9
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.7-beta
  CTBarMod, v8.3.0.9
  CTBuffMod, v8.3.0.9
  CTCore, v8.3.0.9
  CTLibrary, v8.3.0.9
  CTMailMod, v8.3.0.7
  CTMapMod, v8.3.0.8
  CTPartyBuffs, v8.2.5.6
  CTUnitFrames, v8.3.0.9
  DidIDoIt, v1.2.0
  EMAClassic, vv1.13.4-Release-v0.9(121029)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  FloAspectBar, v
  FloTotemBar, v
  GatherMate2, v1.45.4
  Grail, v111
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GrailReputationsclassic, v007
  GrailWhen, v002
  Informant, v8.2.6508 (SwimmingSeadragon)
  ISBoxer, v1.0
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v6.0.2
  QuestLogEx, v1.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  WhatsTraining, v1.8.7
  Wholly, v079
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=908)

**Comment by Nerillida** [comment]
Additionally, Questie maps correctly.

**Comment by smaitch** [comment]
Are you getting this in Orgrimmar, or any other place?  Do you always get this?  Are you mousing over a specific pin in the map?  I have tried this with both Alliance and Horde characters in Classic and am not able to reproduce it at the moment.  I see the code, but it is protected to ensure there is an X value before it tries to use both the X and Y.  I am wondering what data is there that has X defined but not Y.  A fix can be made in code but I would love to be able to reproduce this.

**Comment by Nerillida** [comment]
In Undercity, click onto Silverpine Map.

Date: 2020-07-17 14:37:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Wholly\Wholly.lua line 851:
   attempt to perform arithmetic on local 'y' (a nil value)
Debug:
   Wholly\Wholly.lua:851: OnAcquired()
   ...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:165: AcquirePin()
   Wholly\Wholly.lua:830: RefreshAllData()
   ...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:76: OnMapChanged()
   ...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:529: OnMapChanged()
   ...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:115: OnMapChanged()
   ...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:37: SetMapID()
   ...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:731: NavigateToCursor()
   ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:113:
      ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:105
Locals:
self = <unnamed> {
 SetNudgeSourceMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:166
 GetGlobalPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:253
 PanTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:260
 owningMap = WorldMapFrame {
 }
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:270
 GetNudgeSourceZoomedInMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:175
 SetScaleStyle = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:301
 scaleFactor = 1
 map = WorldMapFrame {
 }
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:199
 OnCanvasSizeChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:279
 ApplyCurrentPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:336
 IsIgnoringGlobalPinScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:287
 endScale = 1.200000
 OnMouseEnter = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:122
 pinTemplate = "WhollyPinsTemplate"
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:134
 texType = "G"
 OnAcquired = <function> defined @Interface\AddOns\Wholly\Wholly.lua:850
 PanAndZoomTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:265
 xcoord = 71.650000
 ApplyCurrentScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:340
 OnLoad = <function> defined @Interface\AddOns\Wholly\Wholly.lua:841
 OnReleased = <function> defined @Interface\AddOns\Wholly\Wholly.lua:860
 OnMapInsetMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:146
 SetNudgeFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:228
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:207
 startScale = 1
 OnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:118
 SetNudgeZoomedInFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:179
 GetNudgeSourceRadius = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:162
 GetNudgeTargetFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:154
 GetFrameLevelType = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:370
 SetAlphaStyle = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:326
 SetScalingLimits = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:291
 SetNudgeSourceRadius = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:158
 SetNudgeVector = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:216
 ycoord = 29.270000
 normalizedX = 0.716500
 SetAlphaLimits = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:316
 npcId = 14729
 0 = <userdata>
 OnCanvasPanChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:275
 OnMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:126
 SetPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:240
 normalizedY = 0.292700
 GetPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:248
 SetNudgeTargetFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:150
 OnMo

![Screen Shot 2020-07-17 at 14 40 15](https://user-images.githubusercontent.com/55858788/87792306-9b28f600-c83b-11ea-9f74-66c11ce12394.png)

The city/town icons are those of Eastern Kingdom  and the character marker is where I am on the world map.

Hovering over a Wholly "!" gives

Date: 2020-07-17 14:43:35
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Wholly\Wholly.lua line 4134:
   attempt to perform arithmetic on field 'y' (a nil value)
Debug:
   Wholly\Wholly.lua:4134: ShowTooltip()
   Wholly\Wholly.lua:846:
      Wholly\Wholly.lua:846
Locals:
self = <table> {
 SortingFunction = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4213
 pinsNeedFiltering = false
 _SetupBlizzardQuestLogSupport = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3694
 configurationScript5 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:545
 _BreadcrumbQuestId = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1283
 Sort = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4184
 _SearchFrameShow = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3401
 configurationScript18 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:602
 mapPinsRegistry = <table> {
 }
 _RegisterSlashCommand = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1991
 currentMaximumTooltipLines = 50
 debug = true
 configurationScript2 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:530
 tooltip = com_mithrandir_WhollyTooltip {
 }
 SortButtonEnter = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4198
 initialUpdateProcessed = false
 ScrollFrame_Update_WithCombatCheck = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3379
 _ColorCodeFromInfo = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1489
 ScrollFrame_Update = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3492
 _PinIndex = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1971
 cachedPanelQuests = <table> {
 }
 _SetupLibDataBroker = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3783
 _SetupDefaults = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3712
 configurationScript10 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:560
 carboniteMapLoaded = false
 configurationScript15 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:579
 playerAliveReceived = false
 _HideTooltip = <function> defined @Interface\AddOns\Wholly\Wholly.lua:2008
 QuestInfoEnter = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3147
 configurationScript12 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:569
 SetCurrentZoneToPanel = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3652
 _NPCInfoSection = <function> defined @Interface\AddOns\Wholly\Wholly.lua:2491
 receivedCalendarUpdateEventList = false
 _RecordTooltipNPCs = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3267
 ShowBreadcrumbInfo = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4088
 _Dropdown_GetText = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1702
 waypoints = <table> {
 }
 configurationScript8 = <function> defined @Interface\AddOns\Wholly\Wholly.lua:551
 _DroppedItemMatchesQuest = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1745
 _TagDeleteConfirm = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4274
 mapPinsTemplateName = "WhollyPinsTemplate"
 _GetBreadcrumbMessage = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3680
 checkedNPCs = <table> {
 }
 color = <table> {
 }
 mapPinsProvider = <table> {
 }
 _SetLevelTwoCurrent = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3668
 dropdownLimit = 40
 npcs = <table> {
 }
 _Dropdown_Create = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1691
 Click = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1452
 RegisteredMapPin = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1982
 preferenceButtons = <table> {
 }
 _DisplayMapFrame = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1668
 _ColorUpdatePreferenceText = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1518
 ToggleSwitch = <function> defined @Interface\AddOns\Wholly\Wholly.lua:4345
 Dropdown_Initialize = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1709
 filteredPinQuests = <table> {
 }
 ScrollFrame_OnLoad = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3361
 filteredPanelQuests = <table> {
 }
 BreadcrumbClick = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1262
 BreadcrumbUpdate = <function> defined @Interface\AddOns\Wholly\Wholly.lua:1296
 _PrettyQuestString = <function> defined @Interface\AddOns\Wholly\Wholly.lua:2620
 pairedConfigurationButton = com_mithr

Then the hover over stops working

So, it's confused which map it's showing.

When I use Mapster, and try to choose Silverpine, it does nothing once the error mentioned has happened. before that error, it works fine.

The error is present with just Wholly/Grail. Fresh download, no other addons. As well as with others.

Ask further if you need to.

**Comment by Nerillida** [comment]
Alliance and Horde

**Comment by Nerillida** [comment]
Damn and double damn
Found error
Classic NPCs
G[1940]={'1421:64.60,,23.60 1421:65.80,25.20 1421:65.80,28.80 1421:67.80,25.80 1421:68.00,34.40 1421:67.40,35.60'}	-- Rot Hide Plague Weaver

Double comma.
That's one of mine from a long while ago. Maybe no other user has been to Silverpine.
Sorry.
Works fine now.
