### ISSUE TITLE
Feature request: key-binding Loremaster

### ISSUE THREAD

**Issue by puggan** [smaitch/Wholly#4]
When doing loremaster-quest, its good to see what loremaster quest i can do, but I often want to get info on non-loremaster quests, so I go in to the settings often.

to avoid it, I use a macro
```
/script WhollyDatabase.showsLoremasterOnly = not WhollyDatabase.showsLoremasterOnly
/script Wholly._CallbackHandler()
```

But whould be nice if it was a keybinding for it, so i don't need to put an macro on my actionbar

**Comment by smaitch** [comment]
A binding has been added to Wholly for Loremaster.
