### ISSUE TITLE
Daily quest in City don't show

### ISSUE THREAD

**Issue by DreamOfHero** [smaitch/Wholly#41]
Hi,

I don't know if is a Grail or Wholly problem, but I found that with all type of quest selected in option, in Big City like Orgrimmar, daily quest is not showed or listed.
There is a solution to that?

Thanks in Advance
Andrea

![image](https://user-images.githubusercontent.com/36561742/100393591-8571db80-303a-11eb-80d4-131e0c4eb4d9.png)
![image](https://user-images.githubusercontent.com/36561742/100393656-acc8a880-303a-11eb-979e-9b195c7c102a.png)
![image](https://user-images.githubusercontent.com/36561742/100393670-bc47f180-303a-11eb-8c01-81e335a75cac.png)

**Comment by yoshimo** [comment]
Do you have an example quest name and I'd that you expect to be there?

**Comment by DreamOfHero** [comment]
this one: https://www.wowhead.com/quest=26572/a-golden-opportunity

*Andrea Medici*


Il giorno ven 27 nov 2020 alle ore 07:53 yoshimo <notifications@github.com>
ha scritto:

**Comment by yoshimo** [comment]
We have 3 different versions of OG if im not mistaken,
mapid 85, which is the OG itself, 86 which is the claw of shadows and 1534 which i don't recognise.
If the NPC is marked for the wrong id, you don't see the quest.
G[42506]={'FH 86:56.53,62.49'}  looks like the fishing npc is misplaced.

@smaitch I think we should make wholly show the mapid on mouseover to help differentiate multiple zones with the same name

**Comment by DreamOfHero** [comment]
The same behavior is with daily quests of the chef Marogg, the one that
give also recipes...
https://www.wowhead.com/npc=42506/marogg#starts

*Andrea Medici*


Il giorno ven 27 nov 2020 alle ore 18:51 yoshimo <notifications@github.com>
ha scritto:

**Comment by smaitch** [comment]
Most likely if the NPC is marked in a map that is not the normal map for showing where that quest is, then that is the problem.  If you are running with an addon like Fortress or Titan Panel, Wholly can provide a data broker to indicate the zone you are in (and its map ID).  Will have to look into this more.

**Comment by DreamOfHero** [comment]
I don't have Fortress or Titan Panel installed.

*Andrea Medici*


Il giorno dom 29 nov 2020 alle ore 16:26 Scott Harrison <
notifications@github.com> ha scritto:

**Comment by yoshimo** [comment]
"+ Ein wütender Fang(26588)[30] <= Razgar(3000000)[43239] 85:65.84,40.86", -- [2]
I think it is just the NPC that is misplaced.

**Comment by smaitch** [comment]
The latest version of Grail (114) on GitHub has the Orgrimmar NPC map IDs updated to 85 (vice 86) so they should appear properly.
