### ISSUE TITLE
Wholly 082 works for TBC, but

### ISSUE THREAD

**Issue by urodoc** [smaitch/Wholly#44]
As per the issues notes here and at Grail, using Wholly 082 with Grail 115 works! It even resolves the prior problem with quests showing as level [255] (although I also did delete all my old Saved Variables for Wholly and Grail, so maybe that fixed the [255] issue.

Only catch currently is that curseforge shows two downloads for Wholly, 082 for retail and 079 for classic (079 does not work for TBC). Needs to be clarified to show 082 for TBC. (I can't speak to what the new classic classic needs).

Great work!

**Comment by smaitch** [comment]
The reason Classic was not updated for a while was because there were no changes for it.  However, the latest update should be made within the day.

**Comment by smaitch** [comment]
Wholly and Grail have both been released for Retail and Classic (which includes Burning Crusade).  The retail and classic versions are separate downloads at the moment.  The next versions are planned to be one unified addon each that supports both retail and classic without separate addons.
