### ISSUE TITLE
TBCC - Cross faction quests

### ISSUE THREAD

**Issue by Sibrylla** [smaitch/Wholly#45]
I am seeing Horde quests while on my alliance character in Feralas.  Havent noticed it in other zones with both faction hubs. 

Thank you for the update!

**Comment by yoshimo** [comment]
It helps a lot if you can name the quests or even better give us their quest ids. It is hard to fix if you need to check the complete zone.

**Comment by Sibrylla** [comment]
From Rok Orhan:
The Ogres of Feralas (lvl43) ID 2975
Dark Ceremony (lvl46) ID 2979
The Ogres of Feralas (lvl44) ID 2980

From Talo Thornhoof:
Dark Heart (lvl 50) ID 3062
Vengeance on the Northspring (lvl50) ID 3063
The Strength of Corruption (lvl52) ID 4120

Sorry, hope this is what you were looking for.

**Comment by smaitch** [comment]
I just pushed a change to Grail https://github.com/smaitch/Grail/commit/f513258da895982bbd3fb4ee33ad9d7674399eef which marks these two quest givers as Horde, which should make those quests unobtainable for Alliance characters.
