### ISSUE TITLE
Option to remove unneeded information on quest popup and world map

### ISSUE THREAD

**Issue by addonaddict** [smaitch/Wholly#49]
Hello,

Is there any possibility to add option to remove quest ID's or make this default addon behavior when installed?
I dont really have use for quest ID's but I dont see any option to not show it

Same question for world map markers that I never have use for...

Example:
![image](https://user-images.githubusercontent.com/73442541/159470405-dce1339f-0da3-4224-9749-38b4432ac2dc.png)

Example 2:
![image](https://user-images.githubusercontent.com/73442541/159470801-8b3ad597-e498-4c87-b6e9-ff0323f870a2.png)

Thank you

**Comment by smaitch** [comment]
The button on the world map can be hidden using the preferences.  Until an option is created to remove the quest number from the QuestFrame is made you can run the command "/run com_mithrandir_whollyQuestInfoFrame:Hide()" if you want.

**Comment by addonaddict** [comment]
Ok thanks, i will look for those preferences
For the quest ID - i tried the command but sadly it resets after each reload
Does this mean you are looking into adding that as an option?

Thanks

**Comment by smaitch** [comment]
Yes, it will reset after a reload.  And yes, I am looking into adding an option to Wholly.  I really would not have thought the quest number was too intrusive, and the purpose of mousing over it is to get all the extra quest information, but adding an option to not show it should be simple enough.

**Comment by smaitch** [comment]
The latest version of Wholly just pushed here (which will be released as 086) has an option to hide the quest number in the Quest Frame.

**Comment by addonaddict** [comment]
Thank you so much!!!
