### ISSUE TITLE
Suggestion: remove / add option to remove Grail server query alert in chat on login

### ISSUE THREAD

**Issue by addonaddict** [smaitch/Wholly#50]
Hello,

Love the addon
Is it possible to add option to remove chat announcement on every login?
Either as global option or set by default when installing addon
I find this info not really important which is why im trying to clean up the chat spams everytime i login / reload

Thank you!

Example:
![image](https://user-images.githubusercontent.com/73442541/159469972-378be83d-3bff-4308-afbc-c8f62a1b86af.png)

**Comment by smaitch** [comment]
This is being handled in ticket https://github.com/smaitch/Grail/issues/293
