### ISSUE TITLE
10.0 DF errors

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Wholly#51]
```
2x FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:545 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
```

**Comment by Malivil** [comment]
In my testing this seems to be fixed by just removing the `parent="InterfaceOptionsFramePanelContainer"` attributes from the frames at the bottom of Wholly.xml

As far as I can tell these are for the Addons options menu? And those seem to be displaying fine after just removing these attributes.

**Comment by yoshimo** [comment]
https://wowpedia.fandom.com/wiki/Patch_10.0.0/API_changes , some settings stuff was deprecated and changed.

**Comment by Malivil** [comment]
Yea, I know but just removing that attribute seems to make it work fine:

![image](https://user-images.githubusercontent.com/1238511/198882842-d45ffe08-811f-4012-8f47-cdf99d065fcb.png)

**Comment by smaitch** [comment]
The latest version of Wholly is now out and should have fixed this.
