### ISSUE TITLE
[Feature Request] Integration with Immersion

### ISSUE THREAD

**Issue by KOVIKO** [smaitch/Wholly#53]
[Immersion](https://www.curseforge.com/wow/addons/immersion) is a popular addon that replaces the quest frame with a talking-heads style frame. Because it replaces the quest frame, using it means I miss out on some features of Wholly, namely the clickable "Breadcrumb quest available" element.

I'd like for this element to be visible when using the Immersion addon and Wholly at the same time.

**Comment by smaitch** [comment]
The code was merged, so I assume the integration is working.
