### ISSUE TITLE
No Longer Functions as of TWW Pre-Patch

### ISSUE THREAD

**Issue by JustForFF** [smaitch/Wholly#58]
Hi! Title is pretty much it, blizzard changed the Quest Log and how they show quests themselves thus I believe it broke Wholly's ability to show the map pins, I am unsure on the effect it has had upon Grail but all of the Grail commands work from what I am seeing so I am assuming it is Wholly

**Comment by yoshimo** [comment]
Grail needs some API changes, which i already reported.

This comes down to several lua errors inside Wholly

`2x Wholly/Wholly.lua:1993: attempt to index field 'mapToContinentMapping' (a nil value)
[string "@Wholly/Wholly.lua"]:1993: in function `_ForcePanelMapArea'
[string "@Wholly/Wholly.lua"]:2912: in function `_ProcessInitialUpdate'
[string "@Wholly/Wholly.lua"]:2645: in function `OnShow'
[string "@Wholly/Wholly.lua"]:4177: in function <Wholly/Wholly.lua:4176>
[string "=[C]"]: in function `Show'
[string "@Wholly/Wholly.lua"]:4673: in function `ToggleUI'
[string "@Wholly/Wholly.lua"]:4491: in function `SlashCommand'
[string "@Wholly/Wholly.lua"]:2100: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5449: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5395>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5101: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5100>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5137: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
self = <table> {
 pinsNeedFiltering = false
 mapPinsRegistry = <table> {
 }
 currentMaximumTooltipLines = 50
 tooltip = com_mithrandir_WhollyTooltip {
 }
 initialUpdateProcessed = false
 dropdownText = "Zeitlose Insel"
 cachedPanelQuests = <table> {
 }
 carboniteMapLoaded = false
 playerAliveReceived = false
 receivedCalendarUpdateEventList = false
 waypoints = <table> {
 }
 mapPinsTemplateName = "WhollyPinsTemplate"
 checkedNPCs = <table> {
 }
 color = <table> {
 }
 mapPinsProvider = <table> {
 }
 dropdownLimit = 40
 npcs = <table> {
 }
 preferenceButtons = <table> {
 }
 filteredPinQuests = <table> {
 }
 filteredPanelQuests = <table> {
 }
 lastUpdate = 0
 checkedGrailVersion = true
 mapFrame = Button {
 }
 coordinates = <table> {
 }
 previousY = 0
 poisToHide = <table> {
 }
 configuration = <table> {
 }
 notificationFrame = Frame {
 }
 s = <table> {
 }
 mapPinsProviderPin = <table> {
 }
 previousX = 0
 mapPinsPool = <table> {
 }
 cachedMapCounts = <table> {
 }
 defaultMaximumTooltipLines = 50
 currentTt = 0
 currentFrame = com_mithrandir_whollyFrame {
 }
 versionNumber = 90
 toggleButton = com_mithrandir_whollyFrameHiddenToggleButton {
 }
 zoneInfo = <table> {
 }
 updateThreshold = 0.100000
 tt = <table> {
 }
 eventDispatch = <table> {
 }
 colorWells = <table> {
 }
 updateDelay = 0.500000
 chooseClosestWaypoint = true
 pins = <table> {
 }
 onlyAddingTooltipToGameTooltip = false
 panelCountLine = "|cFFFFFF000|r/|cFF6666660|r/|cFFFFFFFF0|r/|cFFCC66000|r/|cFFFF00000|r/|cFF0099CC0|r/|cFF66CC660|r/|cFF0099CC0|r/|cFF0000FF0|r/|cFFFF00FF0|r/|cFF00FF000|r/|cFF9966000|r/|cFFFFC0CB0|r/|cFF00FFFF0|r  [0/0]"
 mapPins = <table> {
 }
 mapPinCount = 0
 cachedPinQuests = <table> {
 }
 dungeonTest = <table> {
 }
 maximumSearchHistory = 10
 debug = true
}
ignoreForcingSelection = nil
currentMapId = 0
mapAreaName = "Zeitlose Insel"
(*temporary) = nil
(*temporary) = <table> {
 pinsNeedFiltering = false
 mapPinsRegistry = <table> {
 }
 currentMaximumTooltipLines = 50
 tooltip = com_mithrandir_WhollyTooltip {
 }
 initialUpdateProcessed = false
 dropdownText = "Zeitlose Insel"
 cachedPanelQuests = <table> {
 }
 carboniteMapLoaded = false
 playerAliveReceived = false
 receivedCalendarUpdateEventList = false
 waypoints = <table> {
 }
 mapPinsTemplateName = "WhollyPinsTemplate"
 checkedNPCs = <table> {
 }
 color = <table> {
 }
 mapPinsProvider = <table> {
 }
 dropdownLimit = 40
 npcs = <table> {
 }
 preferenceButtons = <table> {
 }
 filteredPinQuests = <table> {
 }
 filteredPanelQuests = <table> {
 }
 lastUpdate = 0
 checkedGrailVersion = true
 mapFrame = Button {
 }
 coordinates = <table> {
 }
 previousY = 0
 poisToHide = <table> {
 }
 configuration = <table> {
 }
 notificationFrame = Frame {
 }
 s = <table> {
 }
 mapPinsProviderPin = <table> {
 }
 previousX = 0
 mapPinsPool = <table> {
 }
 cachedMapCounts = <table> {
 }
 defaultMaximumTooltipLines = 50
 currentTt = 0
 currentFrame = com_mithrandir_whollyFrame {
 }
 versionNumber = 90
 toggleButton = com_mithrandir_whollyFrameHiddenToggleButton {
 }
 zoneInfo = <table> {
 }
 updateThreshold = 0.100000
 tt = <table> {
 }
 eventDispatch = <table> {
 }
 colorWells = <table> {
 }
 updateDelay = 0.500000
 chooseClosestWaypoint = true
 pins = <table> {
 }
 onlyAddingTooltipToGameTooltip = false
 panelCountLine = "|cFFFFFF000|r/|cFF6666660|r/|cFFFFFFFF0|r/|cFFCC66000|r/|cFFFF00000|r/|cFF0099CC0|r/|cFF66CC660|r/|cFF0099CC0|r/|cFF0000FF0|r/|cFFFF00FF0|r/|cFF00FF000|r/|cFF9966000|r/|cFFFFC0CB0|r/|cFF00FFFF0|r  [0/0]"
 mapPins = <table> {
 }
 mapPinCount = 0
 cachedPinQuests = <table> {
 }
 dungeonTest = <table> {
 }
 maximumSearchHistory = 10
 debug = true
}
(*temporary) = <table> {
 pinsNeedFiltering = false
 mapPinsRegistry = <table> {
 }
 currentMaximumTooltipLines = 50
 tooltip = com_mithrandir_WhollyTooltip {
 }
 initialUpdateProcessed = false
 dropdownText = "Zeitlose Insel"
 cachedPanelQuests = <table> {
 }
 carboniteMapLoaded = false
 playerAliveReceived = false
 receivedCalendarUpdateEventList = false
 waypoints = <table> {
 }
 mapPinsTemplateName = "WhollyPinsTemplate"
 checkedNPCs = <table> {`

`39x Wholly/Wholly.lua:3213: attempt to call global 'GetNumQuestLogRewardCurrencies' (a nil value)
[string "@Wholly/Wholly.lua"]:3213: in function `_PopulateTooltipForQuest'
[string "@Wholly/Wholly.lua"]:1420: in function `ButtonEnter'
[string "*Wholly.xml:27_OnEnter"]:1: in function <[string "*Wholly.xml:27_OnEnter"]:1>

Locals:
self = <table> {
 pinsNeedFiltering = false
 mapPinsRegistry = <table> {
 }
 currentMaximumTooltipLines = 50
 tooltip = com_mithrandir_WhollyTooltip {
 }
 initialUpdateProcessed = false
 dropdownText = "Zeitlose Insel"
 cachedPanelQuests = <table> {
 }
 carboniteMapLoaded = false
 playerAliveReceived = false
 receivedCalendarUpdateEventList = false
 waypoints = <table> {
 }
 mapPinsTemplateName = "WhollyPinsTemplate"
 checkedNPCs = <table> {
 }
 color = <table> {
 }
 mapPinsProvider = <table> {
 }
 dropdownLimit = 40
 npcs = <table> {
 }
 preferenceButtons = <table> {
 }
 filteredPinQuests = <table> {
 }
 filteredPanelQuests = <table> {
 }
 lastUpdate = 0
 checkedGrailVersion = true
 mapFrame = Button {
 }
 coordinates = <table> {
 }
 previousY = 0
 poisToHide = <table> {
 }
 configuration = <table> {
 }
 notificationFrame = Frame {
 }
 s = <table> {
 }
 mapPinsProviderPin = <table> {
 }
 previousX = 0
 mapPinsPool = <table> {
 }
 cachedMapCounts = <table> {
 }
 defaultMaximumTooltipLines = 50
 currentTt = 1
 currentFrame = com_mithrandir_whollyFrame {
 }
 versionNumber = 90
 toggleButton = com_mithrandir_whollyFrameHiddenToggleButton {
 }
 zoneInfo = <table> {
 }
 updateThreshold = 0.100000
 tt = <table> {
 }
 eventDispatch = <table> {
 }
 colorWells = <table> {
 }
 updateDelay = 0.500000
 chooseClosestWaypoint = true
 pins = <table> {
 }
 onlyAddingTooltipToGameTooltip = false
 panelCountLine = "|cFFFFFF0041|r/|cFF6666662|r/|cFFFFFFFF2|r/|cFFCC66000|r/|cFFFF000030|r/|cFF0099CC0|r/|cFF66CC665|r/|cFF0099CC0|r/|cFF0000FF1|r/|cFFFF00FF0|r/|cFF00FF000|r/|cFF9966004|r/|cFFFFC0CB0|r/|cFF00FFFF0|r  [48/85]"
 mapPins = <table> {
 }
 mapPinCount = 0
 cachedPinQuests = <table> {
 }
 dungeonTest = <table> {
 }
 maximumSearchHistory = 10
 debug = true
}
frame = com_mithrandir_whollyFrameScrollFrameButton21 {
 normalText = com_mithrandir_whollyFrameScrollFrameButton21NormalText {
 }
 statusCode = "G"
 questId = 33205
 tag = com_mithrandir_whollyFrameScrollFrameButton21Tag {
 }
}
questId = 33205
aliasQuestId = nil
Grail = <table> {
 bitMaskClassPriest = 256
 totalRawNPCLocations = 181.929200
 bitMaskGenderMale = 8192
 bitMaskCompleted = 1
 tooltip = com_mithrandir_grailTooltip {
 }
 professionCategoryIdMapping = <table> {
 }
 NO_SKILL = -1
 bitMaskClassAll = 402661372
 bitMaskQuestUnused4 = 33554432
 bitMaskQuestLegendary = 4096
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 bitMaskQuestVariableLevel = 255
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 npcNames = <table> {
 }
 diversionMapping = <table> {
 }
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 bitMaskQuestRaid = 128
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 reputationFriendsMaw = <table> {
 }
 classToBitMapping = <table> {
 }
 experimental = false
 professionSkillLineIdMapping = <table> {
 }
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 invalidateGroupCurrentGarrisonTalentQuests = 8
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 questReputations = <table> {
 }
 versionNumber = 122
 invalidateGroupWithering = 1
 bitMaskRaceUnused4 = 128
 bitMaskLevelTooLow = 32
 bitMaskProfession = 4096
 npcsVersionNumber = 15
 bitMaskQuestUnused8 = 536870912
 existsClassicBasic = false
 bitMaskHolidayHarvest = 32
 playerLocale = "deDE"
 buggedQuestsVersionNumber = 0
 factionMapping = <table> {
 }
 bitMaskRaceUnused8 = 2048
 garrisonBuildingMapping = <table> {
 }
 bitMaskRacePandaren = 134217728
 bitMaskRaceUnused`


`1x Wholly/Wholly.lua:2675: attempt to call upvalue 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@Wholly/Wholly.lua"]:2675: in function `_OpenInterfaceOptions'
[string "@Wholly/Wholly.lua"]:4163: in function <Wholly/Wholly.lua:4163>

Locals:
self = <table> {
 pinsNeedFiltering = false
 mapPinsRegistry = <table> {
 }
 currentMaximumTooltipLines = 50
 tooltip = com_mithrandir_WhollyTooltip {
 }
 initialUpdateProcessed = false
 dropdownText = "Zeitlose Insel"
 cachedPanelQuests = <table> {
 }
 carboniteMapLoaded = false
 playerAliveReceived = false
 receivedCalendarUpdateEventList = false
 waypoints = <table> {
 }
 mapPinsTemplateName = "WhollyPinsTemplate"
 checkedNPCs = <table> {
 }
 color = <table> {
 }
 mapPinsProvider = <table> {
 }
 dropdownLimit = 40
 npcs = <table> {
 }
 preferenceButtons = <table> {
 }
 filteredPinQuests = <table> {
 }
 filteredPanelQuests = <table> {
 }
 lastUpdate = 0
 checkedGrailVersion = true
 mapFrame = Button {
 }
 coordinates = <table> {
 }
 previousY = 0
 poisToHide = <table> {
 }
 configuration = <table> {
 }
 notificationFrame = Frame {
 }
 s = <table> {
 }
 mapPinsProviderPin = <table> {
 }
 previousX = 0
 mapPinsPool = <table> {
 }
 cachedMapCounts = <table> {
 }
 defaultMaximumTooltipLines = 50
 currentTt = 0
 currentFrame = com_mithrandir_whollyFrame {
 }
 versionNumber = 90
 toggleButton = com_mithrandir_whollyFrameHiddenToggleButton {
 }
 zoneInfo = <table> {
 }
 updateThreshold = 0.100000
 tt = <table> {
 }
 eventDispatch = <table> {
 }
 colorWells = <table> {
 }
 updateDelay = 0.500000
 chooseClosestWaypoint = true
 pins = <table> {
 }
 onlyAddingTooltipToGameTooltip = false
 panelCountLine = "|cFFFFFF000|r/|cFF6666660|r/|cFFFFFFFF0|r/|cFFCC66000|r/|cFFFF00000|r/|cFF0099CC0|r/|cFF66CC660|r/|cFF0099CC0|r/|cFF0000FF0|r/|cFFFF00FF0|r/|cFF00FF000|r/|cFF9966000|r/|cFFFFC0CB0|r/|cFF00FFFF0|r  [0/0]"
 mapPins = <table> {
 }
 mapPinCount = 0
 cachedPinQuests = <table> {
 }
 dungeonTest = <table> {
 }
 maximumSearchHistory = 10
 debug = true
}
(*temporary) = nil
(*temporary) = "Wholly"
(*temporary) = "attempt to call upvalue 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
InterfaceOptionsFrame_OpenToCategory = nil
`

**Comment by smaitch** [comment]
I have an update coming shortly that gets basic functionality back.

**Comment by yoshimo** [comment]
@smaitch did you intend to push it alongside grail or should I try to fix it first? I just need to bring tool tips back on top of my tww branch

**Comment by smaitch** [comment]
Sorry about that.  I had totally missed that I did not push the changes here when I uploaded the last addon.  I have pushed them now.

**Comment by smaitch** [comment]
Wholly 090 and Grail 122 should have solved this issue.
