### ISSUE TITLE
attempt to index field 'notificationFrame' (a nil value), line 3356

### ISSUE THREAD

**Issue by puggan** [smaitch/Wholly#6]
Date: 2017-09-30 21:46:46
ID: 2
Error occured in: Global
Count: 89
Message: ..\AddOns\Wholly\Wholly.lua line 3356:
   attempt to index field 'notificationFrame' (a nil value)
Debug:
   Wholly\Wholly.lua:3356: update()
   ..\SharedXML\HybridScrollFrame.lua:190: HybridScrollFrame_SetOffset()
   ..\SharedXML\HybridScrollFrame.lua:30:
      ..\SharedXML\HybridScrollFrame.lua:29
   [C]: SetValue()
   ..\SharedXML\HybridScrollFrame.lua:67:
      ..\SharedXML\HybridScrollFrame.lua:57
Locals:
self = com_mithrandir_whollyFrameScrollFrame {
 0 = <userdata>
 buttons = <table> {
 }
 ScrollChild = com_mithrandir_whollyFrameScrollFrameScrollChild {
 }
 scrollUp = com_mithrandir_whollyFrameScrollFrameScrollBarScrollUpButton {
 }
 combatScrollUpdate = true
 range = 945
 scrollDown = com_mithrandir_whollyFrameScrollFrameScrollBarScrollDownButton {
 }
 offset = 49
 scrollBar = com_mithrandir_whollyFrameScrollFrameScrollBar {
 }
 buttonHeight = 16
 update = <function> defined @Interface\AddOns\Wholly\Wholly.lua:3351
 scrollChild = com_mithrandir_whollyFrameScrollFrameScrollChild {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'notificationFrame' (a nil value)"
InCombatLockdown = <function> defined =[C]:-1

**Comment by smaitch** [comment]
I moved the setting of notificationFrame to before events are registered for it.  Will check it in soon.

**Comment by smaitch** [comment]
You can play around with the version of Wholly now in GitHub to see whether this issue reappears.
