### ISSUE TITLE
BfA pre-Patch errors

### ISSUE THREAD

**Issue by DreamOfHero** [smaitch/Wholly#7]
Hi,
after BfA pre-patch this addon cause 3 errors ingame:

1) Message: Interface\AddOns\Wholly\Wholly.lua:5343: hooksecurefunc(): WorldMapFrame_Update is not a function
Stack: Interface\AddOns\Wholly\Wholly.lua:5343: hooksecurefunc(): WorldMapFrame_Update is not a function
[C]: in function `hooksecurefunc'
Interface\AddOns\Wholly\Wholly.lua:5343: in main chunk

2) Message: (null)
this error happen: 21 times, I don't know what it is

3) Message: Binding header WHOLLY is defined more than once in Interface\AddOns\Wholly\Bindings.xml
This error happens: 18 times.

I can solve it by myself or I need to wait a newer version of this addon.

Thanks in advance

**Comment by NERON** [comment]
I think, you should update your grail version

**Comment by RhapsodySL** [comment]
@NERON Still occurs even with a freshly installed Grail and Wholly. It occurs because an instance of WorldMapFrame_Update still exists in Wholly's code; it's not an issue with Grail.

**Comment by javierhimura** [comment]
Grail has not been updated to 8.0 yet, i suppose we should wait first for a Grail update

**Comment by javierhimura** [comment]
@NERON, probably he is using the version available in curseforge, the last version available in curseforge fr both grail and wholly is for 7.3.5

**Comment by DreamOfHero** [comment]
I install addon only with Twitch desktop.
my versions is:
- grail: 095
- wholly: 066

all for wow 7.3.5

**Comment by funjoker** [comment]
Even the Github Version is not working right now.

The QuestList is empty and Map is broken since Blizzard fucked up with UI hooks

**Comment by javierhimura** [comment]
Actually i checked the error, the problem is an incorrect sentence in a line of code of the github version of grail

I create a fork in git with a quick fix
https://github.com/javierhimura/Grail

Whit this change now both github version of grail and wholly work in Pre-Bfa

**Comment by smaitch** [comment]
Both Wholly and Grail have been updated for BfA (on the two addon websites and here on GitHub).
