### ISSUE TITLE
Automatically opens map upon launch and zone change

### ISSUE THREAD

**Issue by shatterpaw** [smaitch/Wholly#8]
I'm seeing an issue with Wholly where the map automatically opens upon character launch, and whenever I change zones.  I've tried the Map toggles in preferences, but none have any affect for this issue.

If I disable Wholly (or Grail), the issue goes away.  

This only started happening with BfA.

**Comment by smaitch** [comment]
This should no longer be a problem with the current versions of Wholly and Grail.
